# Site settings
title: runfastlynda
nickname: runfast<i class="iconfont maozi">&#xf0026;</i>lynda
email: runfastlynda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://runfastlynda.com/" # the base hostname & protocol for your site
twitter_username: runfastlynda
github_username:  runfastlynda
weixinurl: http://7xklz5.com1.z0.glb.clouddn.com/about.3.jpg
# Build settings
# markdown: rdiscount
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

comments :
    provider : duoshuo
    duoshuo :
      short_name : short_name



